[package]
name = "fsm-rs"
version = "0.1.0"
edition = "2021"

[features]
default = []
derive = ["dep:strum"]

[dependencies]
thiserror = "1.0"
strum = { version = "0.26", features = ["derive"], optional = true }

[dev-dependencies]
strum = { version = "0.26", features = ["derive"] }
